Issues
marc-aurele-besner/SimpleNft-MarketPlace pull request #114
Opened 2023-03-18 16:50 UTC by 0xenj

#111 #110 #109  111 was already made

2023-03-18 20:31 UTC, marc-aurele-besner requested changes

2023-03-18 20:31 UTC, marc-aurele-besner commented on contracts/test/shared/functions.t.sol
> +      assertEq(IERC721(tokenContract).balanceOf(sender), balance - 1);
- Let's organize these assertion in a separate function verify_createListing, and reuse it for both helper_createListing
- Add a check balanceOf(marketPlace) + 1

2023-03-18 20:31 UTC, marc-aurele-besner commented on contracts/test/shared/functions.t.sol
> +      assertEq(IERC721(listingDetail.tokenContract).balanceOf(buyer), balance + 1);
I believe these assertion are already in verify_buyListing

2023-03-18 20:31 UTC, marc-aurele-besner commented on contracts/test/shared/functions.t.sol
> +    uint256 balance = IERC721(tokenContract).balanceOf(sender);
Please use more descriptive name, balance of who?

2023-03-19 20:56 UTC, marc-aurele-besner approved these changes

2023-03-19 20:58 UTC, Guillaume-web approved these changes

2023-03-19 21:10 UTC, merged