Enzoniño
marc-aurele-besner/SimpleNft-MarketPlace pull request #2
Opened 2023-02-25 19:09 UTC by 0xenj

2023-02-25 19:52 UTC, marc-aurele-besner reviewed
:+1:

2023-02-25 19:52 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    mapping(address => bool) public moderator;
Nous allons utilisez le contract de openzeppelin AccessControlable pour les roles, mais bel effort :+1:

2023-02-25 19:52 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +        blacklistToken[tokenContract][tokenId] = true;
Nous avons deux options:
- soit nous rajoutons un 3e paramètre de type bool pour utiliser cette fonction pour blacklist et un-blacklist
- sinon nous pouvons créer des fonctions unblacklist pour unblacklist un token ou utilisateur

Je te laisse choisir.

2023-02-25 20:10 UTC, 0xenj commented on contracts/abstracts/Controlable.sol
> +    mapping(address => bool) public moderator;
mince, je vais regarder à quoi il ressemble

2023-02-25 20:14 UTC, 0xenj commented on contracts/abstracts/Controlable.sol
> +        blacklistToken[tokenContract][tokenId] = true;
très bien, je vais essayer de faire les 2

2023-02-25 23:00 UTC, marc-aurele-besner requested changes

2023-02-25 23:00 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +        (success, ) = payable(msg.sender).call{ value: address(this).balance }("");
Nous allons utilisez un token ERC20 pour acheter/vendre les nfts, donc inspire-toi plutôt de notre fonction withdrawERC20Token dans notre contract précédent. Présentement cette logique serait pour withdraw de l'ethereum, mais ce n'est pas ce que le contract va récolter en frais de transaction.

2023-02-26 18:48 UTC, marc-aurele-besner requested changes

2023-02-26 18:48 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +        uint salePrice;
j'aimerais que nous ajoutions:
- seller address
- listing timestamp
- buyer address
- buy timestamp

2023-02-26 20:51 UTC, marc-aurele-besner requested changes

2023-02-26 20:51 UTC, marc-aurele-besner commented on hardhat.config.js
> +require('transaction-retry-tool');
il y a quelques packages que tu a dans les require() qui ne semblent pas avoir été installé sur la repo, donc juste faire certain qu'ils sont installé :+1:

2023-02-26 21:09 UTC, marc-aurele-besner requested changes

2023-02-26 21:09 UTC, marc-aurele-besner commented on .github/CODEOWNERS
> +*       @0xenj
This is not valid, each line represent a file pattern, in this case * is use to represent ALL files, therefore all username need to be on the first line, separated by spaces https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

2023-02-28 14:39 UTC, marc-aurele-besner approved these changes

2023-02-28 14:43 UTC, marc-aurele-besner approved these changes

2023-02-28 14:44 UTC, merged