#49 Create editListingPrice function
marc-aurele-besner/SimpleNft-MarketPlace pull request #50
Opened 2023-03-03 14:28 UTC by BenoitGrilli

created the function.
(not working yet didnt finish in time before the course)

2023-03-03 15:42 UTC, marc-aurele-besner requested changes

2023-03-03 15:42 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    require(listing.buyTimestamp != 0, 'NFT not minted');
change != for ==

2023-03-03 18:11 UTC, BenoitGrilli reviewed
ne compile pas

2023-03-03 18:15 UTC, marc-aurele-besner requested changes

2023-03-03 18:15 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    require(_listings[listingId].salePrice = 0, 'NFT minted');
listingID != listingId
D vs d

2023-03-03 18:15 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +  event ListingPriceChanged(address tokenContract, uint256 tokenId, address buyer);
change address tokenContract, uint256 tokenId pour just uint256 listingId
et même chose dans le emit plus bas

2023-03-04 09:39 UTC, closed without merging

2023-03-04 11:23 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +  // pas besoin de l'adresse buyer puisque on veut change le prix avant le mint
Tu peux retirer les comments s.v.p.

2023-03-04 11:23 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +// que le sale price != du nouveau sale price
Tu peux retirer les comments s.v.p.

2023-03-04 11:23 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    emit ListingPriceChanged(newSalePrice, listingId);
L'ordre n'est pas bon, c'est listingId et par la suite newSalePrice

2023-03-04 11:23 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    require(newSalePrice != _listings[listingId].salePrice, 'New price is the same as the current price');
La logique de la vérification est bonne, mais par contre très peu pertinente, elle rajoute des frais de gas pour exécuter la transaction, et forcément le vendeur n'a aucun avantage à changer le prix pour me même prix, de notre côté, s'il le fait, ça ne change rien...

Par contre, une logique importante que nous ne vérifions pas, est-ce que la personne qui appelle cette fonction est bien le vendeur??? Et Est-ce que le listing est toujours actif???