PR test&issue
marc-aurele-besner/SimpleNft-MarketPlace pull request #56
Opened 2023-03-05 16:38 UTC by 0xenj

- Setup test file, error file
- #42 
- #44 
- #45

2023-03-05 16:50 UTC, marc-aurele-besner requested changes

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return true;
_changeSupportedContract(contractAddress) already return bool
so change for
```solidity
return _changeSupportedContract(contractAddress);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return true;
_changeTransactionFee(newTransactionFee) already return bool
so change for
```solidity
return _changeTransactionFee(newTransactionFee);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return true;
_withdrawTransactionFee() already return bool
so change for
```solidity
return _withdrawTransactionFee();
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return true;
_blacklistToken(tokenContract, tokenId, isBlackListed) already return bool
so change for
```solidity
return _blacklistToken(tokenContract, tokenId, isBlackListed);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return true;
_blacklistUser(userAddress, set) already return bool
so change for
```solidity
return _blacklistUser(userAddress, set);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    }
_isBlacklistedUser(userAddress)  already return bool
so remove the if and just add
```solidity
return _isBlacklistedUser(userAddress);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    }
_isBlacklistedToken(tokenContract, tokenId)  already return bool
so remove the if and just add
```solidity
return _isBlacklistedToken(tokenContract, tokenId);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    }
_isSupportedContract(tokenContract) already return bool
so remove the if and just add
```solidity
return _isSupportedContract(tokenContract);
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    }
blacklistUser[userAddress] already equal bool
so remove the if and just add
```solidity
return blacklistUser[userAddress];
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    }
blacklistToken[tokenContract][tokenId] already equal bool
so remove the if and just add
```solidity
return blacklistToken[tokenContract][tokenId];
```

2023-03-05 16:50 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    }
supportedContracts[tokenContract] already equal bool
so remove the if and just add
```solidity
return supportedContracts[tokenContract];
```

2023-03-05 17:12 UTC, marc-aurele-besner requested changes

2023-03-05 17:12 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return (_isBlacklistedUser(userAddress) == true);
_isBlacklistedUser(userAddress)  already return true or false, no need to add == true

2023-03-05 17:12 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return (_isBlacklistedToken(tokenContract, tokenId) == true);
same as above

2023-03-05 17:12 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    return (_isSupportedContract(tokenContract) == true);
same as above

2023-03-05 17:14 UTC, 0xenj commented
yep, my bad for this

2023-03-05 17:15 UTC, marc-aurele-besner approved these changes

2023-03-05 23:09 UTC, marc-aurele-besner requested changes

2023-03-05 23:09 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    require(_isBlacklistedUser(seller) == false, 'User is blacklisted');
You can simplify this line (and the 2 others by replacing it by
```solidity
require(!_isBlacklistedUser(seller), 'User is blacklisted');
```
Also please add the name of the contract in the revert message, so we can more easily trace back where the error originate, like
```txt
ListingManager: User is blacklisted
```

2023-03-06 16:55 UTC, marc-aurele-besner approved these changes

2023-03-06 18:05 UTC, merged