PR initialize #23
marc-aurele-besner/SimpleNft-MarketPlace pull request #57
Opened 2023-03-05 18:04 UTC by 0xenj

- #23

2023-03-05 18:08 UTC, 0xenj commented on contracts/abstracts/Controlable.sol
> +    _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);
msg.sender or _msgSender()

2023-03-05 18:22 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);
Dans notre cas il n'y a pas vraiment de différence, _msgSender() c'est une fonction internal de openzeppelin qui retourne normalement msg.sender, par contre dans certain cas, ont peu override la logique de _msgSender pour exemple être certain que c'est l'address de la personne qui a créé la transaction à l'origine, si par exemple notre contrat est utilisé par un relayer.

2023-03-05 18:27 UTC, 0xenj commented
J'ai réécris _msgSender(), et sinon les logiques des fonctions init sont bonnes ? Car je ne suis pas sûr d'avoir bien compris

2023-03-05 18:54 UTC, marc-aurele-besner requested changes

2023-03-05 18:54 UTC, marc-aurele-besner commented on contracts/abstracts/Controlable.sol
> +    _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);
Nous pourrions aussi assigner le rôle de Moderateur à la personne qui appelle initialize
et le rôle de tressury, ou passé un argument de type addresss pour ce dernier

2023-03-05 18:54 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    __Controlable_init();
Cette ligne devrait être à l'intérieur de __ListingManager_init {}

2023-03-05 18:54 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    __Controlable_init();
Non il y a déjà une fonction __ValidateSignature_init dans le contract ValidateSignature...

Je demandais que __Controlable_init(); soit transférer à l'intérieur de la logique __ListingManager_init {} puisque cest ListingManager qui inherite de Controlable

2023-03-05 23:05 UTC, marc-aurele-besner requested changes

2023-03-05 23:05 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +  function __ValidateSignature_init(string memory name, string memory version, address treasury) internal onlyInitializing {
Please remove this function, and add the logic inside the main initialize()

2023-03-06 16:53 UTC, marc-aurele-besner commented
> Du coup je comprend mieux la logique mais je ne comprends pas pourquoi dans notre collection nft (ancien projet) nous avions dans initialize appelé une fonction que nous avons défini en dessous qui elle meme appelé les 3 fonction init de chaques contrat ( comme j'avais fait de base au début de la PR)

En fait la logique de ta fonction était bonne, c'est plutôt le nom de la fonction que je n'aimais pas, puisque la fonction intenal avais le nom d'un contrat autre que le contrat dans lequel la fonction était.

Il n'y a pas une seule bonne façon, comme beaucoup des changements que je te demande de faire, c'est souvent simplement pour simplifier ou optimiser le code... Dans notre dernier projet, j'avais uniquement copié la méthodologie de openzeppelin, mais openzeppelin rajoute toujours beaucoup de fonction pour permettre à tous les contacts d'être réutilisé comme bon nous semblent. Dans notre cas nous n'avons pas besoin de toute cette flexibilité et donc ont peu simplifié

2023-03-06 16:54 UTC, marc-aurele-besner approved these changes

2023-03-06 18:04 UTC, Guillaume-web approved these changes

2023-03-06 18:04 UTC, merged