Test foundry
marc-aurele-besner/SimpleNft-MarketPlace pull request #89
Opened 2023-03-13 14:35 UTC by 0xenj

improve test

2023-03-13 18:53 UTC, marc-aurele-besner requested changes

2023-03-13 18:53 UTC, marc-aurele-besner commented on .gitignore
> +.vscode/settings.json
This file has now double everything :rofl:

2023-03-13 18:53 UTC, marc-aurele-besner commented on .vscode/settings.json
> +  "window.zoomLevel": 0.5,
so you need to commit the .vscode/settings.json, before you commit this file, to not have these changes applying yo all of us

2023-03-13 18:53 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    require(_listings[listingId].buyer == address(0) && _listings[listingId].seller != address(0), 'Listing is not active');
require should only be for if the listingId does not exist (> listingCount) otherwise return false

2023-03-13 18:53 UTC, marc-aurele-besner commented on contracts/abstracts/ListingManager.sol
> +    delete _listings[listingId];
this only work for arrray, but not for mapping, please just put price to zero, and have a check that price is > 0 in other functions

2023-03-14 12:25 UTC, marc-aurele-besner approved these changes

2023-03-14 13:06 UTC, BenoitGrilli approved these changes

2023-03-14 13:06 UTC, merged