adding admin function for team management
marc-aurele-besner/SimpleNft-MarketPlace pull request #9
Opened 2023-02-27 08:41 UTC by BenoitGrilli

2023-02-27 08:44 UTC, 0xenj reviewed
on utilise le contrat access control d'openzeppelin il me semble pour les roles

2023-02-27 12:01 UTC, marc-aurele-besner requested changes
Les tests avec foundry pour les mocks contracts dans contracts/tests/mocks/ doivent ce terminé par .t.sol c'est probablement pour cela que ca ne compile pas (présentement ils sont en double)

2023-02-27 12:04 UTC, marc-aurele-besner requested changes

2023-02-27 12:04 UTC, marc-aurele-besner commented on test/BenoitSimpleNftMarketplace.test.js
> +it("Does user can buy NFT (trade eth for token)(should be)") {
Super, pour toutes les idées de tests, petite correction, nous allons acheter/vendre les nfts avec un token ERC20 et non de l'eth :+1: 
(même chose pout tout les tests qui mentionne eth)

2023-02-27 12:10 UTC, BenoitGrilli commented on test/BenoitSimpleNftMarketplace.test.js
> +it("Does user can buy NFT (trade eth for token)(should be)") {
Nous allons créer un token ERC20 pour ensuite l'envoyer sur la plateforme et pouvoir l'échanger contre des NFT ?

2023-02-27 12:17 UTC, marc-aurele-besner commented on test/BenoitSimpleNftMarketplace.test.js
> +it("Does user can buy NFT (trade eth for token)(should be)") {
Dans nos tests, nous allons utiliser le contract MockERC20 qui va nous donner les fonctions de base d'un token et permettre à n'importe qui de minter des tokens comme ils veulent. Quand nous allons déployer sur goerli, nous pourrons utiliser USDC par example (ils ont une faucet qui permet à n'importe qui d'avoir du USDC (sur testnet)) ce qui va être plus réaliste.

2023-02-27 12:19 UTC, BenoitGrilli commented on test/BenoitSimpleNftMarketplace.test.js
> +it("Does user can buy NFT (trade eth for token)(should be)") {
d'accord, j'ai fait les changements.

2023-02-28 13:49 UTC, marc-aurele-besner requested changes

2023-02-28 13:49 UTC, marc-aurele-besner commented on contracts/SimpleNftMarketplace.sol
> +    function transferOwnership(address newOwner) external returns (bool success) {
Nous n'allons pas utiliser cette fonction, puisque nous allons utiliser le contrat AccessControl, et non le contrat Ownable, il y aura la possibilité d'avoir plusieurs roles et plusieurs personnes avec les mêmes rôles, au lieu d'avoir 1 owner unique.

2023-02-28 14:51 UTC, merged